package cmd

const (
	ENV_KEY_DEBUG                 = "RSS_DEBUG"
	ENV_KEY_DEBUG_LEVEL           = "RSS_DEBUG_LEVEL"
	ENV_KEY_REQUEST_TIMEOUT       = "RSS_REQUEST_TIMEOUT"
	ENV_KEY_SERVER_TIMEOUT        = "RSS_SERVER_TIMEOUT"
	ENV_KEY_RULE                  = "RSS_RULE"
	ENV_KEY_HOST                  = "RSS_HOST"
	ENV_KEY_PORT                  = "RSS_PORT"
	ENV_KEY_REDIS                 = "RSS_REDIS"
	ENV_KEY_REDIS_SERVER          = "RSS_SERVER"
	ENV_KEY_REDIS_PASSWD          = "RSS_REDIS_PASSWD"
	ENV_KEY_REDIS_DB              = "RSS_REDIS_DB"
	ENV_MEMORY                    = "RSS_MEMORY"
	ENV_MEMORY_EXPIRATION         = "RSS_MEMORY_EXPIRATION"
	ENV_KEY_HEADLESS_SERVER       = "RSS_HEADLESS_SERVER"
	ENV_KEY_PROXY                 = "RSS_PROXY"
	ENV_KEY_JS_EXEC_TIMEOUT       = "RSS_JS_EXEC_TIMEOUT"
	ENV_KEY_HEADLESS_SLOW_MOTION  = "RSS_HEADLESS_SLOW_MOTION"
	ENV_KEY_HEADLESS_EXEC_TIMEOUT = "RSS_HEADLESS_EXEC_TIMEOUT"
	ENV_KEY_HTTP_FEED_PATH        = "RSS_HTTP_FEED_PATH"
)

type AppFlags struct {
	DEBUG_MODE  bool
	DEBUG_LEVEL string

	HTTP_HOST      string
	HTTP_PORT      int
	HTTP_FEED_PATH string

	REQUEST_TIMEOUT         int
	SERVER_TIMEOUT          int
	JS_EXECUTE_TIMEOUT      int
	HEADLESS_EXCUTE_TIMEOUT int

	REDIS        bool
	REDIS_SERVER string
	REDIS_PASS   string
	REDIS_DB     int

	IN_MEMORY_CACHE      bool
	IN_MEMORY_EXPIRATION int

	HEADLESS_SERVER      string
	HEADLESS_SLOW_MOTION int

	RULES_DIRECTORY string
	PROXY_SERVER    string
}
