FROM alpine:3.16 as Builder
WORKDIR /app
COPY rssc ./
RUN ls -al
RUN apk add upx && \
    upx -9 -o rssc.minify rssc && \
    mv rssc.minify rssc
RUN ls -al

FROM alpine:3.16
COPY --from=Builder /app/rssc /bin/rssc
ENV TZ=Asia/Shanghai
RUN apk add tzdata && \
    cp /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && \
    rm -rf /var/cache/apk/*
EXPOSE 5005
WORKDIR /app
CMD ["rssc"]